name: spark
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
 
  flutter:
    sdk: flutter
  flutter_arc_text: ^0.6.0
  just_audio: ^0.9.37


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  

  fonts:
    - family: sparkFont  
      fonts:
        - asset: assets/BalooBhaijaan2-VariableFont_wght.ttf  
