name: spark
description: TSYP project
publish_to: 'Slim'
version: 1.3.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
 
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_arc_text: ^0.6.0
  flutter_pdfview: ^1.3.4
  just_audio: ^0.9.37

  video_player: ^2.8.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  

  fonts:
    - family: sparkFont  
      fonts:
        - asset: assets/BalooBhaijaan2-VariableFont_wght.ttf  
